In [2]:
import numpy as np

In [3]:
import numpy as np

A = np.array([2, 4, 6])

B = np.array([1, 3, 5])

print(A)
print(B)

[2 4 6]
[1 3 5]


In [4]:
dot = np.dot(A, B)

print(dot)

44


In [5]:
matrix = np.array([[1,2],
                   [3,4]])

print(matrix)


[[1 2]
 [3 4]]


In [6]:
transpose = matrix.T

print(transpose)

[[1 3]
 [2 4]]


In [7]:
A = np.array([[1,2],
              [3,4]])

B = np.array([[5,6],
              [7,8]])

C = np.matmul(A,B)

print(C)

[[19 22]
 [43 50]]


In [8]:
array3d = np.array([

[[1,2],[3,4]],

[[5,6],[7,8]]

])

print(array3d)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [9]:
print(array3d.shape)

(2, 2, 2)


In [10]:
numbers = np.arange(12)

reshaped = numbers.reshape(3,4)

print(reshaped)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [11]:
import numpy as np

A = np.array([2,4,6])
B = np.array([1,3,5])

print("Dot Product =", np.dot(A,B))

matrix = np.array([[1,2],[3,4]])

print("Transpose")

print(matrix.T)

cube = np.arange(8).reshape(2,2,2)

print("3D Array")

print(cube)

Dot Product = 44
Transpose
[[1 3]
 [2 4]]
3D Array
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
